# Generated by Django 4.1.4 on 2023-01-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_management', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
    ]
