# Generated by Django 4.1.4 on 2023-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_management', '0005_userdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
