# Generated by Django 4.1.5 on 2023-01-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acc_management", "0006_alter_userdata_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="is_logged",
            field=models.BooleanField(default=False),
        ),
    ]
