# Generated by Django 4.1.5 on 2023-01-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acc_management", "0007_userdata_is_logged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="id",
        ),
        migrations.AlterField(
            model_name="userdata",
            name="username",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
