# Generated by Django 4.1.5 on 2023-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_management', '0008_remove_userdata_id_alter_userdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
