# Generated by Django 4.1.5 on 2023-01-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acc_management", "0009_alter_userdata_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="inwestycje",
            field=models.JSONField(null=True),
        ),
    ]
