# Generated by Django 4.1.5 on 2023-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acc_management", "0010_userdata_inwestycje"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="inwestycje",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
