# Generated by Django 4.1.5 on 2023-01-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acc_management", "0011_alter_userdata_inwestycje"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="inwestycje",
            new_name="investments",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="email",
        ),
    ]
