# Generated by Django 4.1.5 on 2023-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_management', '0012_rename_inwestycje_userdata_investments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='investments',
            field=models.JSONField(default=dict),
        ),
    ]
