# Generated by Django 4.1.4 on 2022-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inwinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='inwinfo',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inwinfo',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
