# Generated by Django 4.1.4 on 2022-12-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_inwinfo_name_remove_inwinfo_text_inwinfo_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='inwest',
        ),
        migrations.DeleteModel(
            name='InwInfo',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
