# Generated by Django 4.1.4 on 2022-12-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(null=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
