# Generated by Django 4.1.4 on 2022-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stockinfoad'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.SlugField(max_length=20)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
