# Generated by Django 4.1.4 on 2023-01-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stockinfoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfoa',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
