# Generated by Django 4.1.4 on 2023-01-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stockinfoa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfoa',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
