# Generated by Django 4.1.4 on 2023-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_stockinfoa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.SlugField(null=True),
        ),
    ]
