# Generated by Django 4.1.5 on 2023-01-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stockdata_data_alter_stockdata_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockInfo',
        ),
        migrations.DeleteModel(
            name='StockInfoAd',
        ),
    ]
